[project]
name = "Bertalign"
version = "1.1.0"
description = "An automatic multilingual sentence aligner."
urls.homepage = "https://github.com/bfsujason/bertalign"
readme = "README.md"
license-files = ["LICENCE"]
authors = [{ name = "Jason", email = "bfsujason@163.com" }]
requires-python = ">=3.12" # for Lingua
dependencies = [
  "numba>=0.66.0",
  "sentence-transformers>=5.6.1",
  "wtpsplit>=2.2.1",              # mosestokenizer needs PYTHONUTF8 to build
]
# default-optional-dependency-keys = ["cpu"]
# PEP-771 is still in draft, sadly
[project.optional-dependencies]
cpu = ["faiss-cpu>=1.14.3", "onnxruntime>=1.28.0"]
gpu = ["faiss-gpu>=1.14.3", "onnxruntime-gpu>=1.28.0"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
[tool.setuptools]
packages = ["bertalign"]
